// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package menu

import (
	menuapi "lina-core/api/menu"
	"lina-core/internal/service/bizctx"
	menusvc "lina-core/internal/service/menu"
	pluginsvc "lina-core/internal/service/plugin"
	"lina-core/internal/service/role"
)

// ControllerV1 is the menu controller.
type ControllerV1 struct {
	menuSvc   menusvc.Service // menu service
	roleSvc   role.Service    // role service
	bizCtxSvc bizctx.Service  // business context service
}

// NewV1 creates and returns a new menu controller instance.
func NewV1() menuapi.IMenuV1 {
	pluginSvc := pluginsvc.New(nil)
	return &ControllerV1{
		menuSvc:   menusvc.New(pluginSvc),
		roleSvc:   role.New(pluginSvc),
		bizCtxSvc: bizctx.New(),
	}
}
