// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package notice

import (
	noticeapi "lina-plugin-content-notice/backend/api/notice"
	v1 "lina-plugin-content-notice/backend/api/notice/v1"
	noticesvc "lina-plugin-content-notice/backend/internal/service/notice"
)

// ControllerV1 is the notice controller.
type ControllerV1 struct {
	noticeSvc noticesvc.Service // notice service
}

// NewV1 creates and returns a new notice controller instance.
func NewV1() noticeapi.INoticeV1 {
	return NewControllerV1()
}

// NewControllerV1 creates and returns the concrete notice controller instance.
func NewControllerV1() *ControllerV1 {
	return &ControllerV1{
		noticeSvc: noticesvc.New(),
	}
}

// toAPINoticeEntity converts the service-layer plugin-local notice entity into
// the API DTO projection returned through HTTP responses.
func toAPINoticeEntity(e *noticesvc.NoticeEntity) *v1.NoticeEntity {
	if e == nil {
		return nil
	}
	return &v1.NoticeEntity{
		Id:        e.Id,
		Title:     e.Title,
		Type:      e.Type,
		Content:   e.Content,
		FileIds:   e.FileIds,
		Status:    e.Status,
		Remark:    e.Remark,
		CreatedBy: e.CreatedBy,
		UpdatedBy: e.UpdatedBy,
		CreatedAt: e.CreatedAt,
		UpdatedAt: e.UpdatedAt,
		DeletedAt: e.DeletedAt,
	}
}
