// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	authapi "lina-core/api/auth"
	authsvc "lina-core/internal/service/auth"
	"lina-core/internal/service/bizctx"
	"lina-core/internal/service/orgcap"
	pluginsvc "lina-core/internal/service/plugin"
)

// ControllerV1 is the authentication controller.
type ControllerV1 struct {
	authSvc   authsvc.Service // auth service
	bizCtxSvc bizctx.Service  // business context service
}

// NewV1 creates and returns a new authentication controller instance.
func NewV1() authapi.IAuthV1 {
	pluginSvc := pluginsvc.New(nil)
	orgCapSvc := orgcap.New(pluginSvc)
	return &ControllerV1{
		authSvc:   authsvc.New(orgCapSvc),
		bizCtxSvc: bizctx.New(),
	}
}
