// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package usermsg

import (
	"lina-core/api/usermsg"
	usermsgsvc "lina-core/internal/service/usermsg"
)

// ControllerV1 is the user message controller.
type ControllerV1 struct {
	usermsgSvc usermsgsvc.Service // user message service
}

// NewV1 creates and returns a new user message controller instance.
func NewV1() usermsg.IUsermsgV1 {
	return &ControllerV1{
		usermsgSvc: usermsgsvc.New(),
	}
}
