// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dict

import (
	"lina-core/api/dict"
	dictsvc "lina-core/internal/service/dict"
)

// ControllerV1 is the dictionary controller.
type ControllerV1 struct {
	dictSvc dictsvc.Service // dictionary service
}

// NewV1 creates and returns a new dictionary controller instance.
func NewV1() dict.IDictV1 {
	return &ControllerV1{
		dictSvc: dictsvc.New(),
	}
}
