// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dept

import (
	deptapi "lina-plugin-org-center/backend/api/dept"
	v1 "lina-plugin-org-center/backend/api/dept/v1"
	deptsvc "lina-plugin-org-center/backend/internal/service/dept"
)

// ControllerV1 is the department controller.
type ControllerV1 struct {
	deptSvc deptsvc.Service // department service
}

// NewV1 creates and returns a new department controller instance.
func NewV1() deptapi.IDeptV1 {
	return &ControllerV1{deptSvc: deptsvc.New()}
}

// toAPIDeptEntity converts the service-layer department entity into the API DTO projection.
func toAPIDeptEntity(entity *deptsvc.DeptEntity) *v1.DeptEntity {
	if entity == nil {
		return nil
	}
	return &v1.DeptEntity{
		Id:        entity.Id,
		ParentId:  entity.ParentId,
		Ancestors: entity.Ancestors,
		Name:      entity.Name,
		Code:      entity.Code,
		OrderNum:  entity.OrderNum,
		Leader:    entity.Leader,
		Phone:     entity.Phone,
		Email:     entity.Email,
		Status:    entity.Status,
		Remark:    entity.Remark,
		CreatedAt: entity.CreatedAt,
		UpdatedAt: entity.UpdatedAt,
		DeletedAt: entity.DeletedAt,
	}
}
