// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-plugin-demo-source/backend/internal/dao/internal"
)

// pluginDemoSourceRecordDao is the data access object for the table plugin_demo_source_record.
// You can define custom methods on it to extend its functionality as needed.
type pluginDemoSourceRecordDao struct {
	*internal.PluginDemoSourceRecordDao
}

var (
	// PluginDemoSourceRecord is a globally accessible object for table plugin_demo_source_record operations.
	PluginDemoSourceRecord = pluginDemoSourceRecordDao{internal.NewPluginDemoSourceRecordDao()}
)

// Add your custom methods and functionality below.
