// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package role

import (
	"lina-core/api/role"
	pluginsvc "lina-core/internal/service/plugin"
	rolesvc "lina-core/internal/service/role"
)

// ControllerV1 is the role controller.
type ControllerV1 struct {
	roleSvc rolesvc.Service // role service
}

// NewV1 creates and returns a new role controller instance.
func NewV1() role.IRoleV1 {
	pluginSvc := pluginsvc.New(nil)
	return &ControllerV1{
		roleSvc: rolesvc.New(pluginSvc),
	}
}
