// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package post

import (
	postapi "lina-plugin-org-center/backend/api/post"
	v1 "lina-plugin-org-center/backend/api/post/v1"
	postsvc "lina-plugin-org-center/backend/internal/service/post"
)

// ControllerV1 is the post controller.
type ControllerV1 struct {
	postSvc postsvc.Service // post service
}

// NewV1 creates and returns a new post controller instance.
func NewV1() postapi.IPostV1 {
	return &ControllerV1{postSvc: postsvc.New()}
}

// toAPIPostEntity converts the service-layer post entity into the API DTO projection.
func toAPIPostEntity(entity *postsvc.PostEntity) *v1.PostEntity {
	if entity == nil {
		return nil
	}
	return &v1.PostEntity{
		Id:        entity.Id,
		DeptId:    entity.DeptId,
		Code:      entity.Code,
		Name:      entity.Name,
		Sort:      entity.Sort,
		Status:    entity.Status,
		Remark:    entity.Remark,
		CreatedAt: entity.CreatedAt,
		UpdatedAt: entity.UpdatedAt,
		DeletedAt: entity.DeletedAt,
	}
}
