// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysNotifyChannelDao is the data access object for the table sys_notify_channel.
// You can define custom methods on it to extend its functionality as needed.
type sysNotifyChannelDao struct {
	*internal.SysNotifyChannelDao
}

var (
	// SysNotifyChannel is a globally accessible object for table sys_notify_channel operations.
	SysNotifyChannel = sysNotifyChannelDao{internal.NewSysNotifyChannelDao()}
)

// Add your custom methods and functionality below.
