// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysCacheRevisionDao is the data access object for the table sys_cache_revision.
// You can define custom methods on it to extend its functionality as needed.
type sysCacheRevisionDao struct {
	*internal.SysCacheRevisionDao
}

var (
	// SysCacheRevision is a globally accessible object for table sys_cache_revision operations.
	SysCacheRevision = sysCacheRevisionDao{internal.NewSysCacheRevisionDao()}
)

// Add your custom methods and functionality below.
