// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysNotifyMessageDao is the data access object for the table sys_notify_message.
// You can define custom methods on it to extend its functionality as needed.
type sysNotifyMessageDao struct {
	*internal.SysNotifyMessageDao
}

var (
	// SysNotifyMessage is a globally accessible object for table sys_notify_message operations.
	SysNotifyMessage = sysNotifyMessageDao{internal.NewSysNotifyMessageDao()}
)

// Add your custom methods and functionality below.
