// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysJobGroupDao is the data access object for the table sys_job_group.
// You can define custom methods on it to extend its functionality as needed.
type sysJobGroupDao struct {
	*internal.SysJobGroupDao
}

var (
	// SysJobGroup is a globally accessible object for table sys_job_group operations.
	SysJobGroup = sysJobGroupDao{internal.NewSysJobGroupDao()}
)

// Add your custom methods and functionality below.
