// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysLockerDao is the data access object for the table sys_locker.
// You can define custom methods on it to extend its functionality as needed.
type sysLockerDao struct {
	*internal.SysLockerDao
}

var (
	// SysLocker is a globally accessible object for table sys_locker operations.
	SysLocker = sysLockerDao{internal.NewSysLockerDao()}
)

// Add your custom methods and functionality below.
