// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysKvCacheDao is the data access object for the table sys_kv_cache.
// You can define custom methods on it to extend its functionality as needed.
type sysKvCacheDao struct {
	*internal.SysKvCacheDao
}

var (
	// SysKvCache is a globally accessible object for table sys_kv_cache operations.
	SysKvCache = sysKvCacheDao{internal.NewSysKvCacheDao()}
)

// Add your custom methods and functionality below.
