// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysPluginMigrationDao is the data access object for the table sys_plugin_migration.
// You can define custom methods on it to extend its functionality as needed.
type sysPluginMigrationDao struct {
	*internal.SysPluginMigrationDao
}

var (
	// SysPluginMigration is a globally accessible object for table sys_plugin_migration operations.
	SysPluginMigration = sysPluginMigrationDao{internal.NewSysPluginMigrationDao()}
)

// Add your custom methods and functionality below.
