// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysPluginReleaseDao is the data access object for the table sys_plugin_release.
// You can define custom methods on it to extend its functionality as needed.
type sysPluginReleaseDao struct {
	*internal.SysPluginReleaseDao
}

var (
	// SysPluginRelease is a globally accessible object for table sys_plugin_release operations.
	SysPluginRelease = sysPluginReleaseDao{internal.NewSysPluginReleaseDao()}
)

// Add your custom methods and functionality below.
