// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysFileDao is the data access object for the table sys_file.
// You can define custom methods on it to extend its functionality as needed.
type sysFileDao struct {
	*internal.SysFileDao
}

var (
	// SysFile is a globally accessible object for table sys_file operations.
	SysFile = sysFileDao{internal.NewSysFileDao()}
)

// Add your custom methods and functionality below.
