// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysPluginNodeStateDao is the data access object for the table sys_plugin_node_state.
// You can define custom methods on it to extend its functionality as needed.
type sysPluginNodeStateDao struct {
	*internal.SysPluginNodeStateDao
}

var (
	// SysPluginNodeState is a globally accessible object for table sys_plugin_node_state operations.
	SysPluginNodeState = sysPluginNodeStateDao{internal.NewSysPluginNodeStateDao()}
)

// Add your custom methods and functionality below.
