// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysNotifyDeliveryDao is the data access object for the table sys_notify_delivery.
// You can define custom methods on it to extend its functionality as needed.
type sysNotifyDeliveryDao struct {
	*internal.SysNotifyDeliveryDao
}

var (
	// SysNotifyDelivery is a globally accessible object for table sys_notify_delivery operations.
	SysNotifyDelivery = sysNotifyDeliveryDao{internal.NewSysNotifyDeliveryDao()}
)

// Add your custom methods and functionality below.
