// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"lina-core/internal/dao/internal"
)

// sysPluginResourceRefDao is the data access object for the table sys_plugin_resource_ref.
// You can define custom methods on it to extend its functionality as needed.
type sysPluginResourceRefDao struct {
	*internal.SysPluginResourceRefDao
}

var (
	// SysPluginResourceRef is a globally accessible object for table sys_plugin_resource_ref operations.
	SysPluginResourceRef = sysPluginResourceRefDao{internal.NewSysPluginResourceRefDao()}
)

// Add your custom methods and functionality below.
