// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package file

import (
	"lina-core/api/file"
	filesvc "lina-core/internal/service/file"
	"lina-core/internal/service/orgcap"
	pluginsvc "lina-core/internal/service/plugin"
)

// ControllerV1 is the file controller.
type ControllerV1 struct {
	fileSvc filesvc.Service // file service
}

// NewV1 creates and returns a new file controller instance.
func NewV1() file.IFileV1 {
	pluginSvc := pluginsvc.New(nil)
	return &ControllerV1{
		fileSvc: filesvc.New(orgcap.New(pluginSvc)),
	}
}
