// Package crawler implements the MVP picture-card crawler workflow.
package crawler

import (
	"context"
	"fmt"
	"net/url"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TableName stores the plugin-owned crawler job table name.
const TableName = "plugin_rehab_card_crawl_job"

// Service defines the crawler service contract.
type Service interface {
	// List queries crawler jobs with pagination and filters.
	List(ctx context.Context, in ListInput) (*ListOutput, error)
	// Run creates a crawler job and placeholder cards for immediate admin validation.
	Run(ctx context.Context, in RunInput) (int64, error)
}

// Ensure serviceImpl implements Service.
var _ Service = (*serviceImpl)(nil)

// serviceImpl implements Service.
type serviceImpl struct{}

// New creates and returns a crawler service instance.
func New() Service { return &serviceImpl{} }

// Entity describes one crawler job row.
type Entity struct {
	Id             int64       `orm:"id" json:"id"`
	CategoryId     int64       `orm:"category_id" json:"categoryId"`
	Keyword        string      `orm:"keyword" json:"keyword"`
	Provider       string      `orm:"provider" json:"provider"`
	RequestedCount int         `orm:"requested_count" json:"requestedCount"`
	FetchedCount   int         `orm:"fetched_count" json:"fetchedCount"`
	Status         string      `orm:"status" json:"status"`
	Message        string      `orm:"message" json:"message"`
	CreatedAt      *gtime.Time `orm:"created_at" json:"createdAt"`
	UpdatedAt      *gtime.Time `orm:"updated_at" json:"updatedAt"`
}

// ListInput defines crawler job list filters.
type ListInput struct {
	PageNum    int
	PageSize   int
	CategoryId int64
	Status     string
}

// ListOutput defines crawler job list output.
type ListOutput struct {
	List  []*Entity
	Total int
}

// RunInput defines a crawler execution request.
type RunInput struct {
	CategoryId int64
	Keyword    string
	Provider   string
	Count      int
}

// jobSaveRow maps crawler job write fields to database columns.
type jobSaveRow struct {
	CategoryId     int64  `orm:"category_id"`
	Keyword        string `orm:"keyword"`
	Provider       string `orm:"provider"`
	RequestedCount int    `orm:"requested_count"`
	FetchedCount   int    `orm:"fetched_count"`
	Status         string `orm:"status"`
	Message        string `orm:"message"`
}

// cardSaveRow maps generated placeholder cards to database columns.
type cardSaveRow struct {
	CategoryId int64  `orm:"category_id"`
	Title      string `orm:"title"`
	Label      string `orm:"label"`
	ImageUrl   string `orm:"image_url"`
	Source     string `orm:"source"`
	License    string `orm:"license"`
	Difficulty int    `orm:"difficulty"`
	Status     int    `orm:"status"`
	Sort       int    `orm:"sort"`
	Remark     string `orm:"remark"`
}

// List queries crawler jobs with pagination and filters.
func (s *serviceImpl) List(ctx context.Context, in ListInput) (*ListOutput, error) {
	model := g.DB().Model(TableName).Ctx(ctx)
	if in.CategoryId > 0 {
		model = model.Where("category_id", in.CategoryId)
	}
	if in.Status != "" {
		model = model.Where("status", in.Status)
	}
	total, err := model.Count()
	if err != nil {
		return nil, err
	}
	list := make([]*Entity, 0)
	err = model.Page(in.PageNum, in.PageSize).OrderDesc("id").Scan(&list)
	if err != nil {
		return nil, err
	}
	return &ListOutput{List: list, Total: total}, nil
}

// Run creates a crawler job and placeholder cards for immediate admin validation.
func (s *serviceImpl) Run(ctx context.Context, in RunInput) (int64, error) {
	jobId, err := g.DB().Model(TableName).Ctx(ctx).Data(jobSaveRow{CategoryId: in.CategoryId, Keyword: in.Keyword, Provider: in.Provider, RequestedCount: in.Count, Status: "pending", Message: "Creating placeholder cards"}).InsertAndGetId()
	if err != nil {
		return 0, err
	}
	fetched := 0
	for index := 1; index <= in.Count; index++ {
		encodedText := url.QueryEscape(fmt.Sprintf("%s %d", in.Keyword, index))
		_, insertErr := g.DB().Model("plugin_rehab_card").Ctx(ctx).Data(cardSaveRow{CategoryId: in.CategoryId, Title: fmt.Sprintf("%s %d", in.Keyword, index), Label: in.Keyword, ImageUrl: "https://dummyimage.com/512x512/f5f5f5/333333&text=" + encodedText, Source: in.Provider, License: "placeholder", Difficulty: 1, Status: 1, Sort: index, Remark: "Generated by MVP crawler placeholder"}).Insert()
		if insertErr != nil {
			return jobId, insertErr
		}
		fetched++
	}
	_, err = g.DB().Model(TableName).Ctx(ctx).Where("id", jobId).Data(jobSaveRow{FetchedCount: fetched, Status: "completed", Message: "Generated placeholder cards"}).Update()
	return jobId, err
}
