id: monitor-loginlog
name: 系统监控-登录日志
version: v0.1.0
type: source
description: 提供登录日志持久化与治理界面的官方源码插件
author: linapro
license: Apache-2.0
menus:
  - key: plugin:monitor-loginlog:loginlog
    parent_key: monitor
    name: 登录日志
    path: /monitor/loginlog
    component: system/plugin/dynamic-page
    perms: monitor:loginlog:list
    icon: lucide:log-in
    type: M
    sort: 4
    remark: 系统监控插件-登录日志
  - key: plugin:monitor-loginlog:loginlog:query
    parent_key: plugin:monitor-loginlog:loginlog
    name: 日志查询
    perms: monitor:loginlog:query
    type: B
    sort: 1
  - key: plugin:monitor-loginlog:loginlog:remove
    parent_key: plugin:monitor-loginlog:loginlog
    name: 日志删除
    perms: monitor:loginlog:remove
    type: B
    sort: 2
  - key: plugin:monitor-loginlog:loginlog:export
    parent_key: plugin:monitor-loginlog:loginlog
    name: 日志导出
    perms: monitor:loginlog:export
    type: B
    sort: 3
  - key: plugin:monitor-loginlog:loginlog:clear
    parent_key: plugin:monitor-loginlog:loginlog
    name: 清空日志
    perms: monitor:loginlog:clear
    type: B
    sort: 4
