# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "pgsql:postgres:postgres@tcp(127.0.0.1:5432)/linapro?sslmode=disable"
        path: "internal"
        tables: "plugin_monitor_operlog,sys_dict_data"
        removePrefix: "plugin_monitor_"
        importPrefix: "lina-plugin-monitor-operlog/backend/internal"
        descriptionTag: true
        noModelComment: true
