// This file defines dynamic-route review DTOs projected into plugin
// management APIs for install and enable governance dialogs.

package v1

// PluginRouteReviewItem describes one dynamic route exposed by the current
// plugin release during install or enable review.
type PluginRouteReviewItem struct {
	// Method is the normalized HTTP method declared by the dynamic route.
	Method string `json:"method" dc:"Dynamic routing HTTP methods" eg:"GET"`
	// PublicPath is the host-visible public URL served for this dynamic route.
	PublicPath string `json:"publicPath" dc:"The real public path of the host, always starts with /api/v1/extensions/{pluginId}/" eg:"/api/v1/extensions/plugin-demo-dynamic/review-summary"`
	// Access identifies whether the route is public or requires login context.
	Access string `json:"access" dc:"Access level: public=public access login=login access" eg:"login"`
	// Permission is the host permission key enforced for authenticated routes.
	Permission string `json:"permission,omitempty" dc:"Host permission identifier; public route returns empty string" eg:"plugin-demo-dynamic:review:query"`
	// Summary is the short review-friendly route summary.
	Summary string `json:"summary,omitempty" dc:"Dynamic routing summary, derived from the summary in the routing contract" eg:"Query plugin review summary"`
	// Description is the detailed business description declared by the route.
	Description string `json:"description,omitempty" dc:"Dynamic routing description, from description in routing contract" eg:"Returns the review summary information generated by the current version of the dynamic plugin"`
}
